
package eu.artofcoding.mitglieder.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Member", targetNamespace = "http://web.mitglieder.artofcoding.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Member {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeAllDrupalDateToString", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.ChangeAllDrupalDateToString")
    @ResponseWrapper(localName = "changeAllDrupalDateToStringResponse", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.ChangeAllDrupalDateToStringResponse")
    @Action(input = "http://web.mitglieder.artofcoding.eu/Member/changeAllDrupalDateToStringRequest", output = "http://web.mitglieder.artofcoding.eu/Member/changeAllDrupalDateToStringResponse")
    public boolean changeAllDrupalDateToString();

    /**
     * 
     * @param uid
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeDrupalDateToString", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.ChangeDrupalDateToString")
    @ResponseWrapper(localName = "changeDrupalDateToStringResponse", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.ChangeDrupalDateToStringResponse")
    @Action(input = "http://web.mitglieder.artofcoding.eu/Member/changeDrupalDateToStringRequest", output = "http://web.mitglieder.artofcoding.eu/Member/changeDrupalDateToStringResponse")
    public boolean changeDrupalDateToString(
        @WebParam(name = "uid", targetNamespace = "")
        Integer uid);

    /**
     * 
     * @param memberData
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "maintainMember", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.MaintainMember")
    @ResponseWrapper(localName = "maintainMemberResponse", targetNamespace = "http://web.mitglieder.artofcoding.eu/", className = "eu.artofcoding.mitglieder.wsclient.MaintainMemberResponse")
    @Action(input = "http://web.mitglieder.artofcoding.eu/Member/maintainMemberRequest", output = "http://web.mitglieder.artofcoding.eu/Member/maintainMemberResponse")
    public boolean maintainMember(
        @WebParam(name = "memberData", targetNamespace = "")
        MemberData memberData);

}
